using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace CompanyAPI.Models
{
    /// <summary>
    /// Class that encapsulates the Company properties
    /// </summary>
    /// <author>Muhammad Abubaker</author>
    public class Company
    {
        #region PublicProperties

        /// <summary>
        /// Autogenerated Id by the database engine
        /// </summary>
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        /// <summary>
        /// ISIN of the company
        /// </summary>
        [BsonElement("Isin")]
        [Required]
        public string Isin { get; set; }

        /// <summary>
        /// Name of the company
        /// </summary>
        [BsonElement("Name")]
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// STock ticker of the company
        /// </summary>
        [BsonElement("StockTicker")]
        [Required]
        public string StockTicker { get; set; }

        /// <summary>
        /// Excahnge of the company
        /// </summary>
        [BsonElement("Exchange")]
        [Required]
        public string Exchange { get; set; }

        /// <summary>
        /// Website of the company
        /// </summary>
        /// <remarks>This is an optional field</remarks>
        [BsonElement("Website")]
        public string Website { get; set; }
        #endregion

        #region Constructors

        /// <summary>
        /// Default constructor
        /// </summary>
        public Company()
        {

        }

        /// <summary>
        /// Constructor to create a new company object
        /// </summary>
        /// <param name="isin"></param>
        /// <param name="name"></param>
        /// <param name="stockTicker"></param>
        /// <param name="exchange"></param>
        /// <param name="website"></param>
        public Company(string isin, string name, string stockTicker, string exchange, string website)
        {
            Isin = isin;
            Name = name;
            StockTicker = stockTicker;
            Exchange = exchange;
            Website = website;
        }
        #endregion
    }
}
